---
- name: Install Nginx
  ansible.builtin.include_tasks:
    file: "distros/{{ansible_distribution|lower}}-install.yaml"

- name: Find Certificate Path
  ansible.builtin.shell:
    cmd: "certbot certificates --domains {{DOMAIN_NAME}} | grep --perl-regexp --only-matching '(?<=Certificate Path: )(.*)'"
  register: CERTIFICATE_PATH
  changed_when: false
  become: yes

- name: Find Private Key Path
  ansible.builtin.shell:
    cmd: "certbot certificates --domains {{DOMAIN_NAME}} | grep --perl-regexp --only-matching '(?<=Private Key Path: )(.*)'"
  register: PRIVATE_KEY_PATH
  changed_when: false
  become: yes

- name: Add tls.conf
  ansible.builtin.template:
    src: "{{role_path}}/files/templates/tls.conf.j2"
    dest: "/etc/nginx/conf.d/tls.conf"
  become: yes

- name: Add web.conf
  ansible.builtin.copy:
    src: "{{role_path}}/files/web.conf"
    dest: "/etc/nginx/sites-enabled/"
  become: yes

- name: Reload Nginx
  ansible.builtin.include_tasks:
    file: "distros/{{ansible_distribution|lower}}-reload.yaml"
