---
- hosts: localhost
  tasks:
    - name: Load Variables
      ansible.builtin.include_vars: "main.yaml"
    - name: Setup Infra
      ansible.builtin.include_role:
        name: infra

- hosts: vps
  tasks:
    - name: Load Variables
      ansible.builtin.include_vars: "main.yaml"
    - name: Setup Certbot
      ansible.builtin.include_role:
        name: certbot
    - name: Setup Nginx
      ansible.builtin.include_role:
        name: nginx
