---
- name: Generate Terraform Main Config
  ansible.builtin.template:
    src: "{{role_path}}/files/templates/vps/aws/terraform.main.tf.j2"
    dest: "{{role_path}}/terraform/generated.main.tf"

- name: Generate VPS/AWS Variables
  ansible.builtin.template:
    src: "{{role_path}}/files/templates/vps/aws/variables.tf.j2"
    dest: "{{role_path}}/terraform/modules/vps/aws/generated.variables.tf"
