---
- name: Create Certbot Config Directory
  ansible.builtin.file:
    path: /etc/certbot
    state: directory
    mode: "0755"
  become: yes

- name: Generate Credentials
  ansible.builtin.copy:
    content: dns_cloudflare_api_token = "{{CLOUDFLARE.API_TOKEN}}"
    dest: /etc/certbot/cloudflare.ini
    mode: "0600"
  become: yes

- name: Obtain Certificate
  ansible.builtin.shell:
    cmd: |
      certbot certonly \
        --agree-tos \
        --email {{CLOUDFLARE.EMAIL}} \
        --domains {{DOMAIN_NAME}} \
        --no-eff-email \
        --non-interactive \
        --dns-cloudflare \
        --dns-cloudflare-credentials /etc/certbot/cloudflare.ini
  become: yes

